### ISSUE TITLE
Theme hides toolbar

### ISSUE THREAD

**Issue by barrycarr** [jarodise/Dracula-for-Obsidian.md#11]
Hi, 

The current version of the theme hides the toolbar on the left hand side of the main window. If you compare your screenshot of Obsidian in the readme file and compare it with my screen shot, below, you'll see that the toolbar is missing in your screenshot. I'm using version 0.10.11 of Obsidian on Windows 10.

Thanks.

![image](https://user-images.githubusercontent.com/280746/106806244-9b65d300-665f-11eb-8cf3-123e9ce0d156.png)

**Comment by jarodise** [comment]
Hi Barry, thanks for the feedback, the hiding of the tool-bar is actually seen as a feature of this theme rather than a issue, the tool bars on both sides will be automatically shown when you hover the mouse cursor to the sides, otherwise it's hidden for simplicity purpose, do you prefer them to be shown at all times?

**Comment by gdelazzer** [comment]
Personally I would prefer it to always display as the "zone" to have the toolbar to appear is too narrow, especially when using it windowed :)

**Comment by fcy** [comment]
+1 I'd love to have it shown at all times and likewise I first thought it was a bug
